import Head from 'next/head'
<<<<<<< HEAD
import Script from 'next/script'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
=======
import styles from '../styles/Home.module.scss'
>>>>>>> c1b5c73b5f89e3b98576e23f490ff74f7e51d7af

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Amazon Softwares</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script strategy='lazyOnload'>

      </Script>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Amazon Softwares
        </h1>
        <div className="blogs">
          <div className="blogItem">
            <h1>How to learn Javascript</h1>
          </div>
        </div>

        
       
      </main>

      <footer className={styles.footer}>
       Copywrite @ 2022 Amazon Softwares
      </footer>
    </div>
  )
}
