import Head from 'next/head'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Amazon Softwares</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Amazon Softwares
        </h1>
        <div className="blogs">
          <div className="blogItem">
            <h1>How to learn Javascript</h1>
          </div>
        </div>

        
       
      </main>

      <footer className={styles.footer}>
       Copywrite @ 2022 Amazon Softwares
      </footer>
    </div>
  )
}
